import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { detectFormat } from '../packages/viewer-core/src/detection/formatDetection.js';

const CORPUS = new URL('../corpus/', import.meta.url);

interface ManifestEntry {
  format: string;
  sha256?: string;
  description?: string;
}
interface Manifest {
  files: {
    production: Record<string, ManifestEntry>;
    malicious: Record<string, ManifestEntry>;
  };
}

const manifest: Manifest = JSON.parse(
  await readFile(join(CORPUS.pathname, 'manifest.json'), 'utf8'),
);

let passed = 0;
let failed = 0;

function check(ok: boolean, label: string): void {
  if (ok) { passed++; } else { failed++; }
  console.log(`  ${ok ? '✓' : '✗'} ${label}`);
}

for (const category of ['production', 'malicious'] as const) {
  for (const [name, entry] of Object.entries(manifest.files[category])) {
    const rel = `${category}/${name}`;
    let bytes: Buffer;
    try {
      bytes = await readFile(join(CORPUS.pathname, category, name));
    } catch {
      check(false, `${rel} — file missing (run: npm run generate-corpus)`);
      continue;
    }

    // Integrity: the committed/generated bytes must match the manifest hash.
    const actual = createHash('sha256').update(bytes).digest('hex');
    if (!entry.sha256) {
      check(false, `${rel} — no sha256 in manifest`);
    } else {
      check(actual === entry.sha256, `${rel} — sha256${actual === entry.sha256 ? '' : ` mismatch (got ${actual.slice(0, 12)}…)`}`);
    }

    // Format detection: the .zip attack fixtures are fed to the DOCX adapter but
    // are intentionally not DOCX (no [Content_Types].xml), so skip the format
    // assertion for them — their bytes are still integrity-checked above.
    if (!name.endsWith('.zip')) {
      const detected = await detectFormat({ data: new Uint8Array(bytes).buffer });
      // detectFormat returns the coarse family ('image'); the manifest sometimes
      // labels the sub-format (e.g. 'svg'). Normalize before comparing.
      const IMAGE_SUBFORMATS = new Set(['image', 'svg', 'tiff', 'jpeg', 'png', 'gif', 'webp', 'heic']);
      const expected = IMAGE_SUBFORMATS.has(entry.format) ? 'image' : entry.format;
      check(detected === expected, `${rel} — format ${detected === expected ? entry.format : `mismatch (expected ${expected}, got ${detected})`}`);
    }
  }
}

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
